import Head from 'next/head'
import Image from 'next/image'
import { useSelector } from 'react-redux'
import { BsChevronDoubleDown } from 'react-icons/bs'
import { BsArrowRight } from 'react-icons/bs'
import { FaFacebookF } from 'react-icons/fa'
import { BsInstagram } from 'react-icons/bs'
import { FaCcPaypal } from 'react-icons/Fa'
import { FaCcMastercard } from 'react-icons/Fa'
import { FaCcVisa } from 'react-icons/Fa'
import { AiFillYoutube } from 'react-icons/ai'
import { GoDash } from 'react-icons/go'
import { useEffect } from 'react'

export default function Home() {
  const state = useSelector((state) => state)
  useEffect(() => {
    document.getElementById('vid').play()
  }, [])

  return (
    <>
      <Head>
        <title>Borèal Coffee Shop | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-[url('/background_home_image.jpg')] bg-cover bg-center h-screen flex flex-col">
        <div className="flex justify-center items-center flex-col h-screen">
          <div className="flex justify-center items-center">
            <img src="/slogan_image1.png" alt="" className="p-5 pt-44 w-2/3" />
          </div>
          <div className="flex flex-col justify-center items-center">
            <div className="p-10 text-white flex flex-row ">
              <a
                href=""
                className="border py-3 px-5  m-5 font-semibold text-sm flex flex-row"
              >
                DISCOVER BORÉAL{' '}
                <BsArrowRight size={20} className="pl-1 text-[#f78f1e]" />
              </a>
              <a
                href=""
                className="border py-3 px-5 m-5 font-semibold text-sm flex flex-row"
              >
                VISIT OUR WORKSHOP{' '}
                <BsArrowRight size={20} className="pl-1 text-[#f78f1e]" />
              </a>
            </div>
          </div>
          <div className="flex flex-col justify-end h-full pb-5">
            <BsChevronDoubleDown size={30} className="text-white" />
          </div>
        </div>
      </div>
      <div className="flex justify-center items-center flex-col bg-[#f78f1e] p-10">
        <div className="children:p-1">
          <div className="text-white font-semibold ">
            <h1 className="text-sm">BORÉAL NEWSLETTER</h1>
            <h1 className="text-2xl">SUBSCRIBE TO OUR NEWSLETTER</h1>
          </div>
          <div className="flex flex-row">
            <textarea
              name="email"
              id=""
              cols="45"
              rows="1"
              className="resize-none p-3 bg-transparent	border placeholder-white text-white rounded-none"
              placeholder="name@gmail.com"
            ></textarea>
            <div className="flex justify-center items-center  py-3 px-10 bg-white font-semibold text-sm text-[#f78f1e]">
              SUBSCRIBE <BsArrowRight className="pl-1" size={20} />
            </div>
          </div>
        </div>
      </div>
      <div className="lg:grid grid-cols-2 grid-rows-1">
        <div className="row-start-1 row-end-2 self-center col-start-1 col-end-2 h-full w-full lg:max-h-[550px]">
          <img
            src="/block-home-1.jpg"
            alt=""
            className="object-cover object-left w-full h-full  bg-no-repeat "
          />
        </div>
        <div className="flex justify-center row-start-1 row-end-2 self-center col-start-2 col-end-[-1] p-10 bg-white h-full ">
          <div className="lg:max-w-lg flex justify-center flex-col ">
            <div className="flex flex-col md:items-start items-center">
              <h1 className="text-[#f78f1e] font-semibold text-lg font-mono">
                <a href="">THE STORY OF OUR</a>
              </h1>
              <h1 className="font-bold text-4xl">
                <a href="">COFFEE SHOPS</a>
                <GoDash size={35} className="text-[#f78f1e]" />
              </h1>
            </div>
            <p className="font-serif text-gray-500 ">
              From an abandoned storage space to a convivial meeting place in
              the heart of Geneva, our first café opened in April 2009 at Rue du
              Stand 60. <br />
              <br /> Now in 3 locations in Geneva and 2 locations in Zürich,
              customers can expect an amazing experience from bean to cup.
              Boreal Coffee is committed to sourcing the finest quality coffee
              beans from farmers around the world, directly traded, and roasted
              with love each week in our artisanal roastery in Carouge. <br />
              <br /> Boréal Coffee expose photos of
              <a href="" className="text-[#f78f1e]">
                {' '}
                Léonard Fisch
              </a>
              .
            </p>
            <br />
            <br />
            <a href="" className="flex  items-center font-bold text-sm">
              DISCOVER OUR CAFÉS
              <BsArrowRight className="pl-1 text-[#f78f1e]" size={20} />
            </a>
          </div>
        </div>
      </div>
      <div className="lg:grid grid-cols-2 grid-rows-1">
        <div className="row-start-1 row-end-2 self-center col-start-2 col-end-[-1] h-full w-full lg:max-h-[550px]">
          <img
            src="/block-home-2.jpg"
            alt=""
            className="object-cover object-left w-full h-full  bg-no-repeat "
          />
        </div>
        <div className="row-start-1 row-end-2 self-center col-start-1 col-end-2 h-full p-10 bg-white flex justify-center">
          <div className="lg:max-w-lg flex justify-center   flex-col ">
            <div className="flex flex-col md:items-start items-center">
              <h1 className="text-[#f78f1e] font-semibold text-lg font-mono">
                <a href="">FROM BEAN TO CUP AT</a>
              </h1>
              <h1 className="font-bold text-4xl">
                <a href="">BORÉAL'S ROASTERY</a>
                <GoDash size={35} className="text-[#f78f1e]" />
              </h1>
            </div>
            <p className="font-serif text-gray-500	">
              We opened an artisanal roastery in Carouge where our small team of
              dedicated roasters works to match the profiles of the green coffee
              beans we import with a roast that brings out their best
              characteristics.
              <br />
              <br /> And, knowing that we work directly with the farmers
              themselves wherever possible to ensure better livelihoods while
              caring for the environment, your beverage is one to feel good
              about.
              <br /> <br />
            </p>
            <br />
            <a href="" className="flex  items-center font-bold text-sm ">
              LEARN ABOUT OUR ROASTERY
              <BsArrowRight className="pl-1 text-[#f78f1e]" size={20} />
            </a>
          </div>
        </div>
      </div>
      {/*   -----------------------------------------------------------------------------------------------------------   */}
      <div className="grid grid-cols-2">
        <div className="row-start-1 row-end-2 self-center col-start-1 col-span-full sm:h-[415px] md:h-[480px] h-full">
          <div className="relative w-full h-full">
            <video
              autoPlay
              loop
              muted
              className="object-cover object-left h-full lg:w-screen"
              id="vid"
            >
              <source src="/latte.mp4" type="video/mp4" />
              Your browser does not support the video tag.
            </video>
            <div className="absolute top-0 left-0 w-full h-full bg-gradient-to-r opacity-70 from-[#101010] to-[#151515]"></div>
          </div>
        </div>
        <div className="row-start-1 row-end-2 self-center lg:col-start-2 col-start-1 col-end-[-1] lg:max-h-[550px]  ">
          <div className="p-10 justify-center items-center relative ">
            <div className="flex flex-col lg:items-start lg:text-start items-center text-center">
              <h1 className="text-[#f78f1e] font-semibold text-lg font-mono">
                <a href="">JEBREW</a>
              </h1>
              <div className="font-bold text-4xl text-white flex flex-col lg:items-start items-center">
                <a href="">CAN'T MAKE IT TO BORÉAL?</a>
                <GoDash size={35} className="text-[#f78f1e]" />
              </div>
            </div>
            <p className="font-serif text-white	">
              Can't make it to Boreal? Whether you are looking for a hearty mug
              of black coffee in the morning or an after-lunch espresso, learn
              how to brew a perfect cup of coffee for your needs and tastes :
            </p>
            <br />
            <div className="children:text-center grid lg:grid-cols-2 lg:grid-rows-1 grid-cols-1 grid-rows-2">
              <div className="lg:border-y lg:p-5 lg:border-r flex justify-center">
                <img src="/jebrew-icons.png" alt="" />
              </div>
              <div className="lg:border-y lg:p-5 lg:border-l flex justify-center">
                <a
                  href=""
                  className="flex  items-center font-bold text-sm text-[#f78f1e]"
                >
                  TEACH ME HOW TO BREW
                  <BsArrowRight className="pl-1 text-[#f78f1e] text-3xl" />
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
      {/*   -----------------------------------------------------------------------------------------------------------   */}
      <div className="flex lg:flex-row flex-col justify-center items-center bg-[#2c2c2d]">
        <div className="lg:p-5 pt-10 relative lg:w-1/3 w-full flex justify-center">
          <div className="lg:absolute lg:right-0 lg:bottom-[-50px]">
            <img
              src="/coffee-packs.png"
              alt=""
              className="h-36 md:h-32 lg:h-36 object-contain right-0"
            />
          </div>
        </div>
        <div className="text-center w-full pb-5 lg:p-5">
          <p className=" text-[#f78f1e] font-semibold  font-mono">
            LIKE WHAT YOU SEE? CURIOUS TO TASTE OUR LOVINGLY ROASTED BEANS?
          </p>
          <a href="" className=" text-white font-semibold text-xl font-mono">
            TAKE A PIECE OF BOREAL HOME WITH YOU. THIS WAY TO OUR E-SHOP
          </a>
        </div>
      </div>
      {/*   -----------------------------------------------------------------------------------------------------------   */}
      <div className="flex flex-col justify-center items-center">
        <div>
          <div className="flex flex-row  px-16 pt-5 ">
            <div
              className="md:inline-block hidden w-1/2 border-r border-b lg:flex justify-center items-center"
              id="icon1"
            >
              <img src="/coffee_logo.png" alt="" className="h-2/3" />
            </div>
            <div
              className="md:flex hidden w-full  md:flex-row border-r border-b"
              id="findUs"
            >
              <div>
                <h1 className="font-bold py-1 px-2 text-sm">FIND US</h1>
                <p className="font-serif text-gray-800 text-xs py-1 px-2">
                  We have 3 shops in Geneva and 2 in Zurich
                </p>

                <a
                  href=""
                  className="flex py-1 px-2 items-center text-[#f78f1e] text-sm"
                >
                  Discover them
                  <BsArrowRight className="pl-1 text-[#f78f1e]" size={20} />
                </a>
              </div>
              <div className="w-full">
                <img
                  src="/locations-footer.png"
                  className="w-full h-full object-contain p-5"
                  alt=""
                />
              </div>
            </div>

            <div
              className="sm:inline-block hidden w-full border-r border-b p-2"
              id="support"
            >
              <h1 className="font-bold text-sm pb-3">SUPPORT</h1>
              <div className="flex flex-row text-xs">
                <div className="w-1/2">
                  <ul>
                    <li className="pb-1 font-serif text-gray-800">
                      <a href="">Cafés</a>
                    </li>
                    <li className="pb-1  font-serif text-gray-800">
                      <a href="">Coffee catering</a>
                    </li>
                    <li className="pb-1 font-serif text-gray-800">
                      <a href="">Jebrew</a>
                    </li>
                    <li className="pb-1 font-serif text-gray-800">
                      <a href="">Léonard Fisch</a>
                    </li>
                  </ul>
                </div>
                <div className="w-1/2">
                  <ul>
                    <li className="pb-1 font-serif text-gray-800">
                      <a href="">Shop</a>
                    </li>
                    <li className="pb-1 font-serif text-gray-800">
                      <a href="">Terms & Conditions</a>
                    </li>
                    <li className="pb-1 font-serif text-gray-800">
                      <a href="">Contact</a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>

            <div className="flex flex-col w-full border-b" id="lanCurFol">
              <div className="flex flex-row w-full h-1/2  border-b">
                <div className="flex justify-between items-center w-1/2 p-2 border-r">
                  <h1 className="font-bold text-sm ">LANGAUGE</h1>
                  <select
                    name="language"
                    id=""
                    className="font-serif text-gray-800 text-xs"
                  >
                    <option value="EN">EN</option>
                    <option value="FR">FR</option>
                  </select>
                </div>
                <div className="flex justify-between items-center w-1/2  p-2">
                  <h1 className="font-bold text-sm ">CURRENCY</h1>
                  <select
                    name="currency"
                    id=""
                    className="font-serif text-gray-800 text-xs"
                  >
                    <option value="CHF">CHF</option>
                    <option value="EUR">EUR</option>
                  </select>
                </div>
              </div>
              <div className="flex flex-row justify-between items-center h-1/2  p-2">
                <h1 className="font-bold text-sm w-full">FOLLOW US:</h1>
                <div className="flex flex-row justify-between items-center p-5 w-1/2">
                  <FaFacebookF size={15} />
                  <BsInstagram size={15} />
                  <AiFillYoutube size={15} />
                </div>
              </div>
            </div>
          </div>

          <div
            id="footer"
            className="px-16 flex flex-col justify-center items-center lg:flex-row lg:justify-between pt-2 pb-10"
          >
            <div>
              <p className="font-serif text-xs text-grey-800">
                Copyright © 2015 - 2022 Boréal Coffee Shop. All rights reserved.
              </p>
            </div>
            <div className="w-32 flex flex-row justify-between">
              <FaCcPaypal size={25} />
              <FaCcMastercard size={25} />
              <FaCcVisa size={25} />
            </div>
            <div className="w-1/3"></div>
          </div>
        </div>
      </div>
      {/*   -----------------------------------------------------------------------------------------------------------   */}
    </>
  )
}
